### ISSUE TITLE
webshop_public_prices

### ISSUE THREAD

**Issue by jcchoquet** [Yenthe666/website#1]
Hello,

the extra price is always displayed:
![image](https://user-images.githubusercontent.com/29275440/175924666-3418d378-bc7e-4f06-9385-81d254897965.png)

**Comment by Yenthe666** [comment]
Hmm, good point. Let me check it ASAP (best effort)

**Comment by jcchoquet** [comment]
thanks

**Comment by Yenthe666** [comment]
@jcchoquet please give it a try with https://github.com/Yenthe666/website/pull/4, I'd appreciate your feedback :)

**Comment by jcchoquet** [comment]
@Yenthe666 it's ok for me. Thanks
